### ISSUE TITLE
deploy first release of linux-scripts

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j-ide#92] opened 2016-10-06 12:47 UTC
Linux scripts should be deployed once on maven central to enable a stable Oomph build.

**Comment by themetalone** [comment] 2016-10-20 12:12
@maybeec could you provide more details about what I should do here?

**Comment by maybeec** [comment] 2016-10-21 04:48
This has to be done by @hohwille due to code signing.
@hohwille correct me if I am wrong. @PriyankaBelorkar is currently working on finalizing the linux scripts to support the same functionality as the windows script do. However, I would strongly recommend to have a snapshot release of the linux-scripts already available and release the linux scripts as soon as possible as we are highly dependent on them with the Oomph build, which is in testing phase already.

**Comment by maybeec** [comment] 2016-11-04 06:50
relates to #66

**Comment by hohwille** [comment] 2016-11-23 19:12
more or less a duplicate of #66. Will be part of 1.4.0.

**Closed by hohwille** 2016-11-23 19:12 UTC
Labels: oomph-setup, scripts-package
